// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddEnumVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddEnumVSIXPackageString = "7a01e90a-6128-46a0-ab52-aa179ba14d87";
        public static Guid guidAddEnumVSIXPackage = new Guid(guidAddEnumVSIXPackageString);

        public const string guidAddEnumVSIXPackageCmdSetString = "5b336e17-1a3c-4ad2-baa0-3be121d297c5";
        public static Guid guidAddEnumVSIXPackageCmdSet = new Guid(guidAddEnumVSIXPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddItemToolWindowCommandId = 0x0100;
    }
}